spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: <username>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true